<a href="https://colab.research.google.com/github/redinbluesky/DeepLearning_Keypoint/blob/main/03_Deeplearning_기초정리_트랜스포머_모델.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 목차
* [Chapter 03_01_트랜스포머 개념](#chapter03_01)
* [Chapter 03_02_디코더 블록](#chapter03_02)
* [Chapter 03_03_셀프 어텐션](#chapter03_03)
* [Chapter 03_03_01_훈련 가능한 가중치가 없는 셀프 어텐션](#chapter03_03_01)


## Chapter 03_01_트랜스포머 개념 <a class="anchor" id="chapter03_01"></a>
1. 트랜스포머는 자연어 처리(NLP)에서 널리 사용되는 딥러닝 모델로, 시퀀스 데이터를 처리하는 데 뛰어난 성능을 보인다.

2. 트랜스포머의 핵심 구성 요소는 셀프 어텐션(self-attention) 메커니즘과 포지셔널 인코딩(positional encoding)이다.
    - 셀프 어텐션은 입력 시퀀스의 각 단어가 다른 단어들과의 관계를 학습할 수 있도록 한다.
    - 포지셔널 인코딩은 단어의 순서를 모델에 제공하여 시퀀스 정보를 유지한다.

3. 트랜스포머 모델은 인코더-디코더, 또는 인코더만, 디코더만으로 구성될 수 있으며, 다양한 NLP 태스크에 맞게 조정될 수 있다.
    - 인코더-디코더: 번역과 같은 시퀀스-투-시퀀스 태스크에 사용된다.
    - 인코더만: BERT와 같은 사전 학습 모델에 사용된다.
    - 디코더만: GPT와 같은 언어 생성 모델에 사용된다.

4. 모든 토큰을 병렬로 처리하지만 위치 인코딩을 통해 순서 정보를 유지하며, 이는 RNN과 달리 긴 시퀀스에서도 효율적으로 학습할 수 있게 한다.

## Chapter 03_02_디코더 블록 <a class="anchor" id="chapter03_02"></a>
1. 디코더 블록은 인코딩된 입력을 기반으로 다음 단어를 예측하고. 이를 반복하여 최종 출력을 생성한다.

2. 디코더 블록은 셀프 어텐션 메커니즘으로 연결된 많은 층으로 구성되어 있다.

3. 셀프 어텐션 메커니즘은 입력 시퀸스의 각 단어가 다른 단어들과의 관계를 학습할 수 있도록 한다.

1. 5개의 토큰을 가진 샘플 ["모든","여행은","한","걸음부터","시작한다"]를 처리하는 최대 입력 길이가 4인 디코더가 있다고 가정한다.
    - 각 토큰은 3차원 백터를 가진다. (예: "모든" = [0.1, 0.2, 0.3], "여행은" = [0.4, 0.5, 0.6], ...)


## Chapter 03_03_셀프 어텐션 <a class="anchor" id="chapter03_03"></a>
1. 셀프 어텐션은 하나의 입력 시퀸스에 있는 서로 다른 위치의 단어 사이에 가중치를 계산한다.

### Chapter 03_03_01_훈련 가능한 가중치가 없는 셀프 어텐션 <a class="anchor" id="chapter03_03"></a>
1. 다른 입력 원소의 정보를 조합하여 각각의 입력 원소에 대한 문맥 벡터를 계산하는 것을 목표로한다.

2. "너의 모든 여행은 한 걸음부터 시작한다"라는 입력 문장을 예시로 사용한다.

3. 입력 문장을 토큰화하여 ["너의", "모든", "여행은", "한", "걸음부터", "시작한다"]로 나눈다.

4. 각 토큰을 임베딩 벡터로 변환한다. 예를 들어, 각 토큰은 3차원 벡터로 표현될 수 있다.
    - "너의"     = [0.43, 0.15, 0.89]
    - "모든"     = [0.55, 0.87, 0.66]
    - "여행은"   = [0.57, 0.85, 0.64]
    - "한"       = [0.22, 0.58, 0.33]
    - "걸음부터" = [0.77, 0.25, 0.10]
    - "시작한다" = [0.05, 0.80, 0.55]

4. 각 토큰을 셀프어텐션의 입력으로 사용하여, 각 토큰과 다른 토큰과의 관계를 학습한 후 문맥 벡터를 계산한다.

5. "모든"의 어텐션 점수 계산은 아래와 같다.
    - "모든"의 임베딩 벡터와 다른 토큰의 내적을 구한다.
        - "모든"  • "너의" = 0.55*0.43 + 0.87*0.15 + 0.66*0.89 = 0.2365 + 0.1305 + 0.5874 = 0.9544
        - "모든"  • "모든" = 0.55*0.55 + 0.87*0.87 + 0.66*0.66 = 0.3025 + 0.7569 + 0.4356 = 1.495
        - "모든"  • "여행은" = 0.55*0.57 + 0.87*0.85 + 0.66*0.64 = 0.3135 + 0.7395 + 0.4224 = 1.4754
        - "모든"  • "한" = 0.55*0.22 + 0.87*0.58 + 0.66*0.33 = 0.121 + 0.5046 + 0.2178 = 0.8434
        - "모든"  • "걸음부터" = 0.55*0.77 + 0.87*0.25 + 0.66*0.10 = 0.4235 + 0.2175 + 0.066 = 0.707
        - "모든"  • "시작한다" = 0.55*0.05 + 0.87*0.80 + 0.66*0.55 = 0.0275 + 0.696 + 0.363 = 1.0865

In [1]:
import torch

# "너의 모든 여행은 한 걸음부터 시작한다"를 임베딩 벡터로 변환한다.
inputs = torch.tensor(
   [[0.43, 0.15, 0.89], # 너의    (x^1)
   [0.55, 0.87, 0.66], # 모든     (x^2)
   [0.57, 0.85, 0.64], # 여행은   (x^3)
   [0.22, 0.58, 0.33], # 한       (x^4)
   [0.77, 0.25, 0.10], # 걸음부터 (x^5)
   [0.05, 0.80, 0.55]] # 시작한다 (x^6)
)

# 쿼리로 사용할 토큰을 "모든"으로 설정한다.
query = inputs[1] # "모든" (x^2)

# 어텐션 점수를 저장할 텐서를 inputs의 배치 크기와 동일한 크기로 초기화한다.
attention_scores = torch.empty(inputs.size(0))

# 각 토큰에 대해 어텐션 점수를 계산한다.
for i , x_i in enumerate(inputs):
    # 쿼리와 현재 토큰의 내적을 계산한다.
    attention_scores[i] = torch.dot(query, x_i)

print("어텐션 점수:", attention_scores)

어텐션 점수: tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


6. 어텐션 점수를 정규화여 가중치를 구한다.
    - 정규화를 하면 각 토큰의 가중치가 0과 1 사이로 변환되며, 모든 가중치의 합은 1이 된다.
    - 정규화를 하면 해석이 용이하고 모델의 안정성을 높일 수 있다.

In [4]:
attention_weights = torch.softmax(attention_scores, dim=0)
print("어텐션 가중치:", attention_weights)
print("가중치 합:", attention_weights.sum())

어텐션 가중치: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
가중치 합: tensor(1.)


7. 어텐션 가중치와 각 토큰의 임베딩 벡터를 곱한후 합하여 문맥 벡터를 계산한다.
    - 문맥 벡터 = Σ (어텐션 가중치 * 토큰 임베딩 벡터)

8. 문맥 벡터가 의미하는 것은 "모든"이라는 단어가 문장에서 다른 단어들과 어떤 관계를 가지고 있는지를 나타내는 벡터이다. 이 벡터는 "모든"이라는 단어의 의미를 문맥에 맞게 조정하는 역할을 한다.

In [5]:
# 문맥 벡터를 저장할 텐서를 초기화한다.
context_vector = torch.zeros(inputs.size(1))
for i, x_i in enumerate(inputs):
    context_vector += attention_weights[i] * x_i
    print(f"토큰 {i+1} 문맥 벡터:", context_vector)

토큰 1 문맥 벡터: tensor([0.0596, 0.0208, 0.1233])
토큰 2 문맥 벡터: tensor([0.1904, 0.2277, 0.2803])
토큰 3 문맥 벡터: tensor([0.3234, 0.4260, 0.4296])
토큰 4 문맥 벡터: tensor([0.3507, 0.4979, 0.4705])
토큰 5 문맥 벡터: tensor([0.4340, 0.5250, 0.4813])
토큰 6 문맥 벡터: tensor([0.4419, 0.6515, 0.5683])


In [2]:
# 모든 문장에 대한 어텐션 가중치와 문맥 벡터를 출력한다.
# 어텐션 점수를 저장할 6 * 6 텐서 초기화
attention_scores_matrix = torch.empty(inputs.size(0), inputs.size(0))
for i, query in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attention_scores_matrix[i][j] = torch.dot(query, x_j)

print("어텐션 점수 행렬:\n", attention_scores_matrix)

어텐션 점수 행렬:
 tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [4]:
print("inputs:\n", inputs)
print("inputs.T:\n", inputs.T)

inputs:
 tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])
inputs.T:
 tensor([[0.4300, 0.5500, 0.5700, 0.2200, 0.7700, 0.0500],
        [0.1500, 0.8700, 0.8500, 0.5800, 0.2500, 0.8000],
        [0.8900, 0.6600, 0.6400, 0.3300, 0.1000, 0.5500]])


In [5]:
# 행렬곱을 사용해 계산
attention_scores_matrix = torch.matmul(inputs, inputs.T)
print("어텐션 점수 행렬:\n", attention_scores_matrix)

어텐션 점수 행렬:
 tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [6]:
# 어텐션 점수 정규화
attention_weights_matrix = torch.softmax(attention_scores_matrix, dim=1)
print("어텐션 가중치 행렬:\n", attention_weights_matrix)

어텐션 가중치 행렬:
 tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])
